name: html docker

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        docker login -username "elmohtarf" --password ${{ secrets.DOCKERPW }}
        docker image build -t elmohtarf/mm:latest .
        docker push elmohtarf/mm:latest
